### ISSUE TITLE
Forensicator.ps1 command does not work properly

### ISSUE THREAD

**Issue by TheGodOfVodka** [Johnng007/Live-Forensicator#13]
When running the command and after inputing the data the script will freeze at "Gathering Installed Programs". I havent been able to find the reason. All the files seem to be in order.

**Comment by Johnng007** [comment]
@TheGodOfVodka which windows version are you running this on? let me see if i can reproduce.

**Comment by TheGodOfVodka** [comment]
Windows 10 Professional. I checked and I seem to have all the dependencies in check.

**Comment by Johnng007** [comment]
Hi @TheGodOfVodka I have tested with a Windows 10 Professional Instance and the Script worked as expected.
Well here is a walk around for you.
For the Gathering of Installed programs, the script uses the Get-CimInstance and also check for installed programs via Registry.

The check using Get-CimInstance is on line 549.
while the registry check is on line 551.

you can comment out the code on line 549 and see if your issue is resolved.
if not you can comment out 551 while uncommenting 549 to see which of the lines is causing the hang for you.

**Comment by TheGodOfVodka** [comment]
Thank you, the issue was resolved when uncommented the line 549.
It seems that it freezes there because I hevily tampered with the registry,
Once again, thanks for solving the issue.

**Comment by Johnng007** [comment]
Good to Know..☺
